Fix workflow

diff --git a/.github/workflows/github_workflow_simplified.yaml b/.github/workflows/github_workflow_simplified.yaml
--- a/.github/workflows/github_workflow_simplified.yaml
+++ b/.github/workflows/github_workflow_simplified.yaml
@@ -1,96 +1,96 @@
 name: Build, Test and Deploy a .NET Core WebApi to Azure App Service
 
-env: # Change these settings if you like
+env: 
   ARTIFACT_NAME: WebApi
   DOTNET_CORE_VERSION: 10.0.x
   PUBLISH_DIRECTORY: "./out/publish"
+
 on:
-#  Uncomment the following lines to enable automatic deployment on push to main, deployment, or master branches
   push:
     branches:
-     - main
-     - deployment
-     - master 
-
-  # Allows you to run this workflow manually from the Actions tab.
+      - main
+      - deployment
+      - master
   workflow_dispatch:
 
 jobs:
-  check: # checking if the secrets exist (src: https://stackoverflow.com/questions/72925899/github-actions-detect-if-secret-exists)
-      runs-on: ubuntu-latest
-      env:
+  check:
+    runs-on: ubuntu-latest
+    env:
       CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
-      steps:
-        - name: "Check if AZURE_WEBAPP_NAME secret exists"
-          env: 
-            super_secret: ${{ secrets.AZURE_WEBAPP_NAME }}
-          if: ${{ env.super_secret == '' }}
-          run: 'echo "echo the repository secret \"AZURE_WEBAPP_NAME\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions\" to create it"; exit 1;'
-    
-        - name: "Check if AZURE_WEBAPP_PUBLISH_PASSWORD secret exists"
-          env: 
-            super_secret: ${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}
-          if: ${{ env.super_secret == '' }}
-          run: 'echo "echo the repository secret \"AZURE_WEBAPP_PUBLISH_PASSWORD\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions \" to create it"; exit 1;'
-    
-        - name: "Check if AZURE_WEBAPP_PUBLISH_USERNAME secret exists"
-          env: 
-            super_secret: ${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME }}
-          if: ${{ env.super_secret == '' }}
-          run: 'echo "echo the repository secret \"AZURE_WEBAPP_PUBLISH_USERNAME\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions\" to create it"; exit 1;'
-    
-        - name: "Check if WEBAPI_PROJECT_FOLDER secret exists"
-          env: 
-            super_secret: ${{ secrets.WEBAPI_PROJECT_FOLDER }}
-          if: ${{ env.super_secret == '' }}
-          run: 'echo "echo the repository secret \"WEBAPI_PROJECT_FOLDER\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions\" to create it"; exit 1;'
-        
-  build:
+    steps:
+      - name: Check if CONNECTION_STRING exists
+        if: ${{ env.CONNECTION_STRING == '' }}
+        run: |
+          echo "Repository secret 'CONNECTION_STRING' is missing!"
+          exit 1
 
+      - name: Check if AZURE_WEBAPP_NAME secret exists
+        if: ${{ secrets.AZURE_WEBAPP_NAME == '' }}
+        run: |
+          echo "Repository secret 'AZURE_WEBAPP_NAME' is missing!"
+          exit 1
+
+      - name: Check if AZURE_WEBAPP_PUBLISH_PASSWORD secret exists
+        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD == '' }}
+        run: |
+          echo "Repository secret 'AZURE_WEBAPP_PUBLISH_PASSWORD' is missing!"
+          exit 1
+
+      - name: Check if AZURE_WEBAPP_PUBLISH_USERNAME secret exists
+        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME == '' }}
+        run: |
+          echo "Repository secret 'AZURE_WEBAPP_PUBLISH_USERNAME' is missing!"
+          exit 1
+
+      - name: Check if WEBAPI_PROJECT_FOLDER secret exists
+        if: ${{ secrets.WEBAPI_PROJECT_FOLDER == '' }}
+        run: |
+          echo "Repository secret 'WEBAPI_PROJECT_FOLDER' is missing!"
+          exit 1
+
+  build:
     runs-on: ubuntu-latest
     needs: check
     steps:
-    
-    - uses: actions/checkout@v4
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v4
-      with:
-        dotnet-version: ${{env.DOTNET_CORE_VERSION}}
+      - uses: actions/checkout@v4
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
 
-    - name: Restore dependencies
-      run: dotnet restore
+      - name: Restore dependencies
+        run: dotnet restore
       
-    - name: Build
-      run: dotnet build --no-restore
+      - name: Build
+        run: dotnet build --no-restore
     
-    - name: Test
-      run: dotnet test --no-build --verbosity normal
+      - name: Test
+        run: dotnet test --no-build --verbosity normal
     
-    - name: Publish
-      run: dotnet publish ./${{ secrets.WEBAPI_PROJECT_FOLDER }} --output ${{env.PUBLISH_DIRECTORY}} --configuration Release 
+      - name: Publish
+        run: dotnet publish ./${{ secrets.WEBAPI_PROJECT_FOLDER }} --output ${{ env.PUBLISH_DIRECTORY }} --configuration Release 
     
-    - name: Publish Artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: ${{ env.ARTIFACT_NAME }}
-        path: ${{ env.PUBLISH_DIRECTORY}}
+      - name: Publish Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.ARTIFACT_NAME }}
+          path: ${{ env.PUBLISH_DIRECTORY }}
 
   deploy:
     runs-on: ubuntu-latest
     needs: [check, build]
     steps:
+      - name: Download artifact from build job
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ env.ARTIFACT_NAME }}
+          path: ${{ env.PUBLISH_DIRECTORY }}
 
-    - name: Download artifact from build job
-      uses: actions/download-artifact@v4
-      with:
-        name: ${{ env.ARTIFACT_NAME }}
-        path: ${{ env.PUBLISH_DIRECTORY}}
-
-     # Deploy to Azure Web apps
-    - name: 'Deploy to Azure App Service'
-      uses: azure/webapps-deploy@v3
-      with: 
-        app-name: ${{ secrets.AZURE_WEBAPP_NAME }} # Replace with your app name
-        publish-profile: <publishData><publishProfile profileName="${{secrets.AZURE_WEBAPP_NAME}} - Zip Deploy" publishMethod="ZipDeploy" publishUrl="${{ secrets.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net:443" userName="${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME }}" userPWD="${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}" destinationAppUrl="http://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
-        package: '${{ env.PUBLISH_DIRECTORY}}'
-        clean: true
+      - name: Deploy to Azure App Service
+        uses: azure/webapps-deploy@v3
+        with:
+          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
+          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
+          package: '${{ env.PUBLISH_DIRECTORY }}'
+          clean: true
